<?php

namespace ProductBundle\Repository;

/**
 * GrindRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrindRepository extends \Doctrine\ORM\EntityRepository
{
}
