<?php

namespace ProductBundle\Repository;

/**
 * ProcessingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcessingRepository extends \Doctrine\ORM\EntityRepository
{
}
