<?php

namespace ProductBundle\Repository;

/**
 * Product_IRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Product_IRepository extends \Doctrine\ORM\EntityRepository
{
}
