<?php

namespace ProductBundle\Repository;

/**
 * RoastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoastRepository extends \Doctrine\ORM\EntityRepository
{
}
