<?php

namespace PageBundle\Repository;

/**
 * Product_TRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Product_TRepository extends \Doctrine\ORM\EntityRepository
{
}
