<?php

namespace PageBundle\Repository;

/**
 * Shopping_Cart_TRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Shopping_Cart_TRepository extends \Doctrine\ORM\EntityRepository
{
}
