page:
    resource: "@PageBundle/Resources/config/routing.yml"
    prefix:   /
farm:
    resource: "@FarmBundle/Resources/config/routing.yml"
    prefix:   /farm
product:
    resource: "@ProductBundle/Resources/config/routing.yml"
    prefix:   /product
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user
region:
    resource: "@RegionBundle/Resources/config/routing.yml"
    prefix:   /region
