ProductBundle\Entity\Grade:
    type: entity
    table: Grade
    repositoryClass: ProductBundle\Repository\GradeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            length: '100'
            unique: true
    lifecycleCallbacks: {  }
