<?php

namespace FarmBundle\Repository;

/**
 * CultivarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CultivarRepository extends \Doctrine\ORM\EntityRepository
{
}
