<?php

namespace FarmBundle\Repository;

/**
 * Farm_AwardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Farm_AwardRepository extends \Doctrine\ORM\EntityRepository
{
}
