FarmBundle\Entity\Certification:
    type: entity
    table: Certification
    repositoryClass: FarmBundle\Repository\CertificationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            length: '100'
            unique: true
    lifecycleCallbacks: {  }
