FarmBundle\Entity\Farm_Award:
    type: entity
    table: Farm_Award
    repositoryClass: FarmBundle\Repository\Farm_AwardRepository

    fields:
        place:
            type: string
            id: true
            length: '4'
            nullable: true
        year:
            id: true
            type: integer
    manyToOne:
            farm:
              targetEntity: Farm_I
              inversedBy: farm_awards
              joinColumn:
                name: farm_id
                referencedColumnName: id
            award:
                targetEntity: Award
                inversedBy: farm_awards
                joinColumn:
                    id: true
                    name: award_id
                    referencedColumnName: id
    lifecycleCallbacks: {  }
