ProductBundle\Entity\Product_I:
    type: entity
    table: Product_I
    repositoryClass: ProductBundle\Repository\Product_IRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        image:
            type: string
            length: 255
        rank:
            type: integer
        description:
            type: string
            length: 255
    oneToMany:
        presentations:
            targetEntity: Presentation
            mappedBy: product
        reviews:
            targetEntity: Review
            mappedBy: product
    manyToOne:
        farm:
          targetEntity: FarmBundle\Entity\Farm_I
          inversedBy: products
          joinColumn:
            name: farm_id
            referencedColumnName: id
        cultivar:
            targetEntity: FarmBundle\Entity\Cultivar
            joinColumn:
                name: cultivar_id
                referencedColumnName: id
        grade:
            targetEntity: Grade
            joinColumn:
                name: grade_id
                referencedColumnName: id
        processing:
            targetEntity: Processing
            joinColumn:
                name: processing_id
                referencedColumnName: id
        flavor:
            targetEntity: Flavor
            joinColumn:
                name: flavor_id
                referencedColumnName: id
    lifecycleCallbacks: {  }