ProductBundle\Entity\Review:
    type: entity
    table: Review
    repositoryClass: ProductBundle\Repository\ReviewRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        user:
            type: string
            length: '50'
            column: user_id
        date:
            type: date
        rate:
            type: integer
        comment:
            type: text
        reviewSubject:
            type: string
            length: '50'
            column: review_subject
    manyToOne:
        product:
            targetEntity: Product_I
            inversedBy: reviews
            joinColumn:
                name: product_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
