UserBundle\Entity\Address:
    type: entity
    table: Address
    repositoryClass: UserBundle\Repository\AddressRepository

    fields:
        fullname:
            type: string
            length: 255
            id: true
            column: Fullname
        line_1:
            type: string
            length: 255
        line_2:
            type: string
            length: 255
        city:
            type: string
            length: 255
        state:
            type: string
            length: 255
        country:
            type: string
            length: 255
        zip:
            type: string
            length: 255
    manyToOne:
        user:
            targetEntity: User
            inversedBy: adrresses
            joinColumn:
                name: user_id
                referencedColumnName: email

    lifecycleCallbacks: {  }
