UserBundle\Entity\User:
    type: entity
    table: User
    repositoryClass: UserBundle\Repository\UserRepository

    fields:
        username:
            type: string
            length: '30'
        firstname:
            type: string
            length: '50'
        lastname:
            type: string
            length: '50'
        email:
            type: string
            id: true
            length: 255
            unique: true
        password:
            type: string
            length: 255
    oneToMany:
        addresses:
            targetEntity: Address
            cascade: [ "persist","remove" ]
            mappedBy: user
   
    lifecycleCallbacks: {  }
