<?php

namespace FarmBundle\Repository;

/**
 * AwardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AwardRepository extends \Doctrine\ORM\EntityRepository
{
}
