product_information:
    path:     /{farm}/{product}/{presentation}
    defaults: { _controller: ProductBundle:Default:product}

product_add_presentation_to_cart:
    path:     /addToCart
    defaults: { _controller: ProductBundle:Default:addToCart}

product_search_presentation:
    path:     /searchPresentation
    defaults: { _controller: ProductBundle:Default:searchPresentation}

product_remove_presentation:
    path:     /removePresentation
    defaults: { _controller: ProductBundle:Default:removePresentation}

product_presentation_price:
    path:     /presentation/getPrice
    defaults: { _controller: ProductBundle:Default:presentationGetPrice}