FarmBundle\Entity\Species:
    type: entity
    table: Species
    repositoryClass: FarmBundle\Repository\SpeciesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            length: '100'
    lifecycleCallbacks: {  }
