user_index:
    path:   /
    defaults:   { _controller: UserBundle:User:index }
    
user_articules:
    path:   /articules/{page}
    defaults:   { _controller: UserBundle:User:articules , page:1 }
    requirements:
        page: \d+
        
user_create:
    path:   /create
    defaults:   { _controller: UserBundle:User:create }
    
user_read:
    path:   /read/{id}
    defaults:   { _controller: UserBundle:User:read }
    
user_update:
    path:   /update/{id}
    defaults:   { _controller: UserBundle:User:update }
    
user_delete:
    path:   /delete/{id}
    defaults:   { _controller: UserBundle:User:delete }