PageBundle\Entity\Shopping_Cart_T:
    type: entity
    table: Shopping_Cart_T
    repositoryClass: PageBundle\Repository\Shopping_Cart_TRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pageTitle:
            type: string
            length: '30'
        cartTitle:
            type: string
            length: '30'
        productTitle:
            type: string
            length: '30'
        farmTitle:
            type: string
            length: '30'
        descriptionTitle:
            type: string
            length: '30'
        weightTitle:
            type: string
            length: '30'
        roastTitle:
            type: string
            length: '30'
        grindTitle:
            type: string
            length: '30'
        unitPriceTitle:
            type: string
            length: '30'
        quantityTitle:
            type: string
            length: '30'
        subTotalTitle:
            type: string
            length: '30'
        totalTitle:
            type: string
            length: '30'
        actionTitle:
            type: string
            length: '30'
        removeButton:
            type: string
            length: '30'
        shippingTitle:
            type: string
            length: '30'
        continueButton:
            type: string
            length: '30'
        checkOutButton:
            type: string
            length: '30'
        emptyCartTitle:
            type: string
            length: '50'
    lifecycleCallbacks: {  }
