product_information:
    path:     /{farm}/{product}/{presentation}
    defaults: { _controller: ProductBundle:Default:product}

product_add_presentation_to_cart:
    path:     /addToCart
    defaults: { _controller: ProductBundle:Default:addToCart}

product_search_presentation:
    path:     /searchPresentation
    defaults: { _controller: ProductBundle:Default:searchPresentation}