<?php

namespace ProductBundle\Repository;

/**
 * FlavorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlavorRepository extends \Doctrine\ORM\EntityRepository
{
}
