RegionBundle\Entity\Region:
    type: entity
    table: Region
    repositoryClass: RegionBundle\Repository\RegionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
        image1:
            type: string
            length: 255
        image_description1:
            type: string
            length: 255
        image2:
            type: string
            length: 255
        image_description2:
            type: string
            length: 255
        image3:
            type: string
            length: 255
        image_description3:
            type: string
            length: 255
        description:
            type: string
            length: 255
        organoleptic_characteristics:
            type: string
            length: 255
        information:
            type: string
            length: 255
        latitude:
            type: float
        longitude:
            type: float
        zoom:
            type: integer
    lifecycleCallbacks: {  }
