<?php

namespace Proxies\__CG__\PageBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Home_T extends \PageBundle\Entity\Home_T implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'id', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'descriptionTitle', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'descriptionInfo', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'bannerImage', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'product1', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'product2', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'product3', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'product4', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'product5', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'product6', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'farm'];
        }

        return ['__isInitialized__', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'id', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'descriptionTitle', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'descriptionInfo', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'bannerImage', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'product1', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'product2', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'product3', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'product4', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'product5', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'product6', '' . "\0" . 'PageBundle\\Entity\\Home_T' . "\0" . 'farm'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Home_T $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionTitle($descriptionTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionTitle', [$descriptionTitle]);

        return parent::setDescriptionTitle($descriptionTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionTitle', []);

        return parent::getDescriptionTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionInfo($descriptionInfo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionInfo', [$descriptionInfo]);

        return parent::setDescriptionInfo($descriptionInfo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionInfo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionInfo', []);

        return parent::getDescriptionInfo();
    }

    /**
     * {@inheritDoc}
     */
    public function setBannerImage($bannerImage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBannerImage', [$bannerImage]);

        return parent::setBannerImage($bannerImage);
    }

    /**
     * {@inheritDoc}
     */
    public function getBannerImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBannerImage', []);

        return parent::getBannerImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setFarm(\FarmBundle\Entity\Farm_I $farm = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFarm', [$farm]);

        return parent::setFarm($farm);
    }

    /**
     * {@inheritDoc}
     */
    public function getFarm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFarm', []);

        return parent::getFarm();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct1(\ProductBundle\Entity\Product_I $product1 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct1', [$product1]);

        return parent::setProduct1($product1);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct1', []);

        return parent::getProduct1();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct2(\ProductBundle\Entity\Product_I $product2 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct2', [$product2]);

        return parent::setProduct2($product2);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct2', []);

        return parent::getProduct2();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct3(\ProductBundle\Entity\Product_I $product3 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct3', [$product3]);

        return parent::setProduct3($product3);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct3', []);

        return parent::getProduct3();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct4(\ProductBundle\Entity\Product_I $product4 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct4', [$product4]);

        return parent::setProduct4($product4);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct4', []);

        return parent::getProduct4();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct5(\ProductBundle\Entity\Product_I $product5 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct5', [$product5]);

        return parent::setProduct5($product5);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct5()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct5', []);

        return parent::getProduct5();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct6(\ProductBundle\Entity\Product_I $product6 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct6', [$product6]);

        return parent::setProduct6($product6);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct6()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct6', []);

        return parent::getProduct6();
    }

}
