<?php

namespace Proxies\__CG__\PageBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Shopping_Cart_T extends \PageBundle\Entity\Shopping_Cart_T implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'id', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'pageTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'cartTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'productTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'farmTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'descriptionTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'weightTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'roastTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'grindTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'unitPriceTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'quantityTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'subTotalTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'totalTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'actionTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'removeButton', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'shippingTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'continueButton', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'checkOutButton', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'emptyCartTitle'];
        }

        return ['__isInitialized__', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'id', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'pageTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'cartTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'productTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'farmTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'descriptionTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'weightTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'roastTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'grindTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'unitPriceTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'quantityTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'subTotalTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'totalTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'actionTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'removeButton', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'shippingTitle', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'continueButton', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'checkOutButton', '' . "\0" . 'PageBundle\\Entity\\Shopping_Cart_T' . "\0" . 'emptyCartTitle'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Shopping_Cart_T $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageTitle($pageTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageTitle', [$pageTitle]);

        return parent::setPageTitle($pageTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageTitle', []);

        return parent::getPageTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setCartTitle($cartTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCartTitle', [$cartTitle]);

        return parent::setCartTitle($cartTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getCartTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCartTitle', []);

        return parent::getCartTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductTitle($productTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductTitle', [$productTitle]);

        return parent::setProductTitle($productTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductTitle', []);

        return parent::getProductTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setFarmTitle($farmTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFarmTitle', [$farmTitle]);

        return parent::setFarmTitle($farmTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getFarmTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFarmTitle', []);

        return parent::getFarmTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionTitle($descriptionTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionTitle', [$descriptionTitle]);

        return parent::setDescriptionTitle($descriptionTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionTitle', []);

        return parent::getDescriptionTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeightTitle($weightTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeightTitle', [$weightTitle]);

        return parent::setWeightTitle($weightTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeightTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeightTitle', []);

        return parent::getWeightTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoastTitle($roastTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoastTitle', [$roastTitle]);

        return parent::setRoastTitle($roastTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoastTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoastTitle', []);

        return parent::getRoastTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrindTitle($grindTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrindTitle', [$grindTitle]);

        return parent::setGrindTitle($grindTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrindTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrindTitle', []);

        return parent::getGrindTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnitPriceTitle($unitPriceTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnitPriceTitle', [$unitPriceTitle]);

        return parent::setUnitPriceTitle($unitPriceTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnitPriceTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnitPriceTitle', []);

        return parent::getUnitPriceTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantityTitle($quantityTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantityTitle', [$quantityTitle]);

        return parent::setQuantityTitle($quantityTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantityTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantityTitle', []);

        return parent::getQuantityTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubTotalTitle($subTotalTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubTotalTitle', [$subTotalTitle]);

        return parent::setSubTotalTitle($subTotalTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubTotalTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubTotalTitle', []);

        return parent::getSubTotalTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalTitle($totalTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalTitle', [$totalTitle]);

        return parent::setTotalTitle($totalTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalTitle', []);

        return parent::getTotalTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setActionTitle($actionTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActionTitle', [$actionTitle]);

        return parent::setActionTitle($actionTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getActionTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActionTitle', []);

        return parent::getActionTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemoveButton($removeButton)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemoveButton', [$removeButton]);

        return parent::setRemoveButton($removeButton);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemoveButton()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemoveButton', []);

        return parent::getRemoveButton();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingTitle($shippingTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingTitle', [$shippingTitle]);

        return parent::setShippingTitle($shippingTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingTitle', []);

        return parent::getShippingTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setContinueButton($continueButton)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContinueButton', [$continueButton]);

        return parent::setContinueButton($continueButton);
    }

    /**
     * {@inheritDoc}
     */
    public function getContinueButton()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContinueButton', []);

        return parent::getContinueButton();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheckOutButton($checkOutButton)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheckOutButton', [$checkOutButton]);

        return parent::setCheckOutButton($checkOutButton);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheckOutButton()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheckOutButton', []);

        return parent::getCheckOutButton();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmptyCartTitle($emptyCartTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmptyCartTitle', [$emptyCartTitle]);

        return parent::setEmptyCartTitle($emptyCartTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmptyCartTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmptyCartTitle', []);

        return parent::getEmptyCartTitle();
    }

}
